export const statsMap = {
    "cost": "cost",
    "abilityhaste": "ability haste",
    "attackdamage": "attack damage",
    "abilitypower": "ability power",
    "armor": "armor",
    "health": "health",
    "lethality": "lethality",
    "magicpenetration": "magic penetration",
    "magicresist": "magic resist",
    "mana": "mana",
    "movespeed": "movement speed",
    "percentarmorpenetration": "armor penetration",
    "percentattackspeed": "attack speed %",
    "percentbasehealthregen": "health regen %",
    "percentbasemanaregen": "mana regen %",
    "percentcriticalstrikechance": "crit chance %",
    "percentcriticalstrikedamage": "crit damage %",
    "percenthealandshieldpower": "heal & shield power %",
    "percentlifesteal": "lifesteal %",
    "percentmagicpenetration": "magic penetration %",
    "percentmovespeed": "movement speed %",
    "percentomnivamp": "omnivamp %",
    "percenttenacity": "tenacity %"
}